const {app,BrowserWindow,dialog,ipcMain,shell,safeStorage}=require('electron');
const fs=require('fs'),path=require('path'),https=require('https');
let win; const base=()=>app.getPath('userData');
function file(name){return path.join(base(),name)}
function read(name,fallback){try{return JSON.parse(fs.readFileSync(file(name),'utf8'))}catch{return fallback}}
function write(name,value){const dst=file(name);fs.mkdirSync(path.dirname(dst),{recursive:true});const tmp=dst+'.tmp';fs.writeFileSync(tmp,JSON.stringify(value,null,2),'utf8');fs.renameSync(tmp,dst)}
function state(){return read('projects.json',{projects:[]})}
function save(s){write('projects.json',s);return s}
function id(){return require('crypto').randomUUID()}
function project(s,i){return s.projects.find(p=>p.id===i)}
function ensureLocal(p){if(!p||typeof p!=='string'||!path.isAbsolute(p))throw Error('无效文件路径');return p}
function makeWindow(){win=new BrowserWindow({width:1320,height:870,minWidth:960,minHeight:650,backgroundColor:'#08111f',title:'PROJECT NEXUS 工程工作站',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:false}});win.loadFile('index.html');win.on('closed',()=>win=null)}
app.whenReady().then(()=>{makeWindow();app.on('activate',()=>{if(!win)makeWindow()})});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
ipcMain.handle('load',()=>state());
ipcMain.handle('create-project',(_e,name)=>{name=String(name||'').trim().slice(0,120);if(!name)throw Error('项目名称不能为空');const s=state();s.projects.push({id:id(),name,links:[],createdAt:new Date().toISOString()});return save(s)});
async function addLink(e,i,type){const s=state(),p=project(s,i);if(!p)throw Error('项目不存在');const x=await dialog.showOpenDialog(win,{title:type==='folder'?'选择工程文件夹':'选择工程文件',properties:type==='folder'?['openDirectory']:['openFile','multiSelections']});if(x.canceled)return s;for(const fn of x.filePaths){if(!p.links.some(z=>z.path.toLowerCase()===fn.toLowerCase()))p.links.push({path:fn,type,addedAt:new Date().toISOString()})}return save(s)}
ipcMain.handle('pick-folder',addLinkWrapper('folder'));ipcMain.handle('pick-file',addLinkWrapper('file'));
function addLinkWrapper(t){return (e,i)=>addLink(e,i,t)}
ipcMain.handle('remove-link',(_e,i,index)=>{const s=state(),p=project(s,i);if(!p)throw Error('项目不存在');if(!Number.isInteger(index)||index<0||index>=p.links.length)throw Error('无效索引');p.links.splice(index,1);return save(s)});
ipcMain.handle('open-path',async(_e,p)=>{p=ensureLocal(p);if(!fs.existsSync(p))throw Error('找不到文件：'+p);const err=await shell.openPath(p);if(err)throw Error(err);return true});
ipcMain.handle('open-project',async(_e,i)=>{const p=project(state(),i);if(!p)throw Error('项目不存在');const l=p.links.find(x=>fs.existsSync(x.path));if(!l)throw Error('该项目尚未映射有效文件夹或文件');const err=await shell.openPath(l.path);if(err)throw Error(err);return true});
ipcMain.handle('fullscreen',()=>{win.setFullScreen(!win.isFullScreen());return win.isFullScreen()});
ipcMain.handle('get-settings',()=>{const s=read('settings.json',{});delete s.secret;return {...s,hasKey:fs.existsSync(file('apikey.enc'))}});
ipcMain.handle('save-settings',(_e,s)=>{const old=read('settings.json',{});const x={provider:String(s.provider||'自定义'),url:String(s.url||'').trim(),model:String(s.model||'').trim()};const u=new URL(x.url);if(u.protocol!=='https:'&&!(['localhost','127.0.0.1'].includes(u.hostname)&&u.protocol==='http:'))throw Error('模型地址必须使用 HTTPS（本机 Ollama 除外）');write('settings.json',x);if(s.key){if(!safeStorage.isEncryptionAvailable())throw Error('系统加密不可用，密钥未保存');fs.writeFileSync(file('apikey.enc'),safeStorage.encryptString(String(s.key)))}return {...x,hasKey:fs.existsSync(file('apikey.enc'))}});
function requestJSON(url,body,key){return new Promise((resolve,reject)=>{const u=new URL(url);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))return reject(Error('只允许 HTTPS 或本机模型地址'));const http=u.protocol==='https:'?require('https'):require('http');const req=http.request(u,{method:'POST',timeout:60000,headers:{'Content-Type':'application/json',...(key?{Authorization:'Bearer '+key}: {})}},res=>{let raw='';res.on('data',c=>{raw+=c;if(raw.length>2e6)req.destroy(Error('模型响应过大'))});res.on('end',()=>{let x;try{x=JSON.parse(raw)}catch{return reject(Error('模型返回非 JSON 数据'))}if(res.statusCode>=400)return reject(Error('HTTP '+res.statusCode+'：'+(x.error?.message||raw.slice(0,260))));resolve(x)})});req.on('error',reject);req.on('timeout',()=>req.destroy(Error('模型响应超时')));req.end(JSON.stringify(body))})}
ipcMain.handle('chat',async(_e,payload)=>{const s=read('settings.json',{});if(!s.url||!s.model)throw Error('请先设置模型地址和模型名称');const base=s.url.replace(/\/+$/,'');const endpoint=base.endsWith('/chat/completions')?base:base+(base.endsWith('/v1')?'':'/v1')+'/chat/completions';let key='';if(fs.existsSync(file('apikey.enc'))){if(!safeStorage.isEncryptionAvailable())throw Error('无法解密密钥');key=safeStorage.decryptString(fs.readFileSync(file('apikey.enc')))}const messages=[{role:'system',content:'你是 PROJECT NEXUS 工程助手。请使用简体中文回答。不要虚构项目进度。'},{role:'user',content:String(payload?.message||'').slice(0,12000)}];if(!messages[1].content.trim())throw Error('请输入问题');const r=await requestJSON(endpoint,{model:s.model,messages,stream:false},key);return String(r.choices?.[0]?.message?.content||'模型未返回文本')});
ipcMain.handle('import-history',async()=>{const d=await dialog.showOpenDialog(win,{title:'选择 ChatGPT 导出的 conversations.json',filters:[{name:'JSON',extensions:['json']}],properties:['openFile']});if(d.canceled)return {count:0};const p=d.filePaths[0];const stats=fs.statSync(p);if(stats.size>150*1024*1024)throw Error('导出文件过大，请先拆分');const arr=JSON.parse(fs.readFileSync(p,'utf8'));if(!Array.isArray(arr))throw Error('请选择 ChatGPT 导出的 conversations.json');const index=arr.map(x=>({title:String(x.title||'未命名对话').slice(0,200),date:x.create_time||null}));write('chat_titles.json',index);return {count:index.length}});
