
'use strict';
const api=window.nexus;
const isFloat=new URLSearchParams(location.search).get('float')==='1';
if(isFloat)document.body.classList.add('float');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
const btn=(name,act,more='')=>'<button type="button" data-act="'+act+'" '+more+'>'+name+'</button>';
let db={projects:[],works:[],apps:[],roots:[]},page=isFloat?'ai':'home',pid='',profiles={},settings={},uploadImage='',chatMessages=[],busy=false,query='',appKind='常用',activeError='',chatDraft='',historyAllowed=false,historyItems=[];
function safeErr(e){const x=String(e?.message||e||'未知错误');return x.replace(/^Error invoking remote method '[^']+': Error:\s*/,'').slice(0,1100)}
function notify(message,kind='ok'){const t=$('toast');if(!t)return;t.textContent=message;t.style.color=kind==='error'?'#ffacb5':'#95ecd2';}
function frame(){
 $('root').innerHTML='<div class="layout"><aside class="sidebar"><div class="brand">◆ NEXUS</div><div class="muted" style="margin:0 9px 18px">中文工程 · 智能工作中心</div><div id="navigation"></div><div class="side-foot">● 本地工作站<br><small>源工程保持原位 · 离线可用</small></div></aside><main class="main"><header class="top"><div><div class="muted">PROJECT NEXUS / ENGINEERING CONSOLE</div><div class="title" id="section-title">工程指挥中心</div></div><div class="top-actions">'+btn('✧ AI 悬浮窗','float-open')+btn('⛶ 全屏切换','fullscreen-toggle')+'</div></header><div class="content" id="content"></div></main></div><div id="toast" role="status" aria-live="polite" class="toast"></div>';
 const nav=[['home','▦ 指挥中心'],['projects','◈ 工程项目'],['files','▤ 智能文件柜'],['work','☷ 工作任务'],['apps','▷ 软件启动台'],['ai','✧ AI 智能助手'],['settings','⚙ 设置 / 数据']];
 $('navigation').innerHTML=nav.map(([id,title])=>'<button type="button" class="nav '+(page===id?'active':'')+'" data-act="nav" data-id="'+id+'">'+title+'</button>').join('');
}
function percentage(p){const a=p.tasks||[];return a.length?Math.round(100*a.filter(x=>x.verified).length/a.length):null}
function projectCard(p){const n=percentage(p),links=(p.links||[]).length;return '<div class="card project-card"><div class="card-meta"><span class="pill">'+esc(p.kind||'自定义')+'</span><span class="muted">'+links+' 处映射</span></div><h3>'+esc(p.name)+'</h3><p>'+links+' 个主工程文件或目录 · '+(n===null?'未设置验收任务':'验收进度 '+n+'%')+'</p><div class="progress"><div style="width:'+(n||0)+'%"></div></div><div class="actions">'+btn('↗ 打开工程','open-project','data-id="'+esc(p.id)+'" class="primary"')+btn('查看项目抽屉','select-project','data-id="'+esc(p.id)+'"')+'</div></div>'}
function breadcrumb(title,desc){return '<div class="section-heading"><div><div class="eyebrow">WORKSPACE / '+esc(page.toUpperCase())+'</div><h1 class="headline">'+title+'</h1><p class="desc">'+desc+'</p></div></div>'}
function home(){return breadcrumb('所有工作，一眼掌控','集中打开工程、查看任务进度，不用再翻找桌面文件。')+'<div class="cards stat-grid"><div class="card"><div class="muted">项目总数</div><div class="stat">'+db.projects.length+'</div><p>本地项目统一管理</p></div><div class="card"><div class="muted">文件映射</div><div class="stat">'+db.projects.reduce((s,p)=>s+(p.links||[]).length,0)+'</div><p>只保存路径，不复制原件</p></div><div class="card"><div class="muted">待完成任务</div><div class="stat">'+(db.projects.reduce((s,p)=>s+(p.tasks||[]).filter(t=>!t.verified).length,0)+db.works.filter(w=>!w.done).length)+'</div><p>任务需要人工验收</p></div></div><div class="toolbar headline-toolbar"><h2>我的项目</h2>'+btn('＋ 创建项目','create-project','class="primary"')+btn('打开 AI 助手','navigate-ai')+'</div><div class="cards">'+(db.projects.map(projectCard).join('')||'<div class="card empty">还没有项目。点击“创建项目”，然后关联真实的工程文件夹。</div>')+'</div>'}
function selectProject(id){pid=id;setPage('projects')}
function projectOptions(selected=''){return db.projects.map(p=>'<option value="'+esc(p.id)+'" '+(p.id===selected?'selected':'')+'>'+esc(p.name)+'</option>').join('')}
function projectDetail(){const p=db.projects.find(x=>x.id===pid);if(!p)return '<div class="panel">请选择一个项目查看文件和任务。</div>';const n=percentage(p);
return '<div class="panel"><div class="project-detail-header"><div><span class="pill">'+esc(p.kind||'工程')+'</span><h2>'+esc(p.name)+'</h2><p class="muted">直接进入工程，不需要先打开文件资源管理器搜索</p></div>'+btn('↗ 一键打开工程','open-project','data-id="'+esc(p.id)+'" class="primary"')+'</div><div class="columns"><section><h3>工程文件抽屉</h3><div class="toolbar">'+btn('＋ 添加文件夹','pick-folder','data-id="'+esc(p.id)+'"')+btn('＋ 添加主工程文件','pick-file','data-id="'+esc(p.id)+'"')+'</div><div class="listing">'+((p.links||[]).map((l,i)=>'<div class="list-item"><span><strong>'+(l.type==='folder'?'📁 ':'📄 ')+esc(l.path.split(/[\\/]/).pop())+'</strong><small>'+esc(l.path)+'</small></span><div class="actions">'+btn('打开','open-path','data-path="'+esc(l.path)+'"')+btn('定位','reveal','data-path="'+esc(l.path)+'"')+btn('移除','remove-link','data-id="'+esc(p.id)+'" data-index="'+i+'" title="只移除索引，不删除原文件"')+'</div></div>').join('')||'<div class="empty">尚未映射。点击上方添加真实工程目录或 .SLDASM / .wbpj / Unity 工程主文件。</div>')+'</div></section><section><h3>验收进度 <span class="muted">'+(n===null?'未设置':n+'%')+'</span></h3><div class="progress"><div style="width:'+(n||0)+'%"></div></div><div class="toolbar"><input id="new-task" placeholder="例如：完成网格划分并验证质量">'+btn('添加验收任务','add-task','data-id="'+esc(p.id)+'"')+'</div><div class="listing">'+((p.tasks||[]).map(t=>'<label class="list-item task"><span><input type="checkbox" data-act="toggle-task" data-id="'+esc(p.id)+'" data-task="'+esc(t.id)+'" '+(t.verified?'checked':'')+'> '+esc(t.title)+'</span><span class="pill">'+(t.verified?'已验收':'待验收')+'</span></label>').join('')||'<div class="empty">尚无任务。进度不会因为聊天次数自动上涨。</div>')+'</div></section></div></div>';
}
function projects(){return breadcrumb('工程项目','每个项目有独立的文件抽屉、主工程入口和验收进度。')+'<div class="toolbar">'+btn('＋ 新建项目','create-project','class="primary"')+'</div><div class="cards">'+(db.projects.map(p=>projectCard(p)).join('')||'<div class="empty card">暂无工程项目。你可以自由创建，不限制项目数量。</div>')+'</div>'+(pid?projectDetail():'')}
function files(){return breadcrumb('智能文件柜','优先人工映射；支持授权目录扫描。所有工程原文件保持原位。')+'<div class="panel"><h3>已授权扫描目录</h3><div class="toolbar">'+btn('＋ 授权文件夹','add-root')+'</div><div class="muted">'+(db.roots||[]).map(x=>'<div class="file-path">📁 '+esc(x)+'</div>').join('')+'</div><p class="muted">当前版本只记录授权目录，不自动移走文件。AI 归属建议需经过核对。</p></div>'+db.projects.map(p=>'<div class="panel"><div class="row-between"><h3>📂 '+esc(p.name)+'</h3><div class="toolbar">'+btn('添加目录','pick-folder','data-id="'+esc(p.id)+'"')+btn('添加文件','pick-file','data-id="'+esc(p.id)+'"')+'</div></div>'+((p.links||[]).map((l,i)=>'<div class="list-item"><span>'+esc(l.path)+'</span><div class="actions">'+btn('打开','open-path','data-path="'+esc(l.path)+'"')+btn('定位','reveal','data-path="'+esc(l.path)+'"')+btn('取消映射','remove-link','data-id="'+esc(p.id)+'" data-index="'+i+'"')+'</div></div>').join('')||'<p class="muted">暂无关联文件</p>')+'</div>').join('')}
function work(){return breadcrumb('工作任务','既能管理工程，也能记录课程、学习、科研和其他日常工作。')+'<div class="panel"><h3>添加新的工作</h3><div class="toolbar"><input id="work-title" placeholder="输入要完成的工作">'+btn('＋ 添加工作','create-work','class="primary"')+'</div></div><div class="panel"><h3>工作清单</h3>'+((db.works||[]).map(w=>'<label class="list-item task"><span><input type="checkbox" data-act="toggle-work" data-id="'+esc(w.id)+'" '+(w.done?'checked':'')+'> '+esc(w.title)+'</span><span class="pill">'+(w.done?'已完成':'进行中')+'</span></label>').join('')||'<div class="empty">当前没有工作任务。</div>')+'</div>'}
function apps(){const kinds=['常用','工程设计','学习办公','开发工具','其他','全部'];let xs=db.apps||[];if(appKind==='常用')xs=xs.filter(x=>x.pinned);else if(appKind!=='全部')xs=xs.filter(x=>x.kind===appKind);if(query)xs=xs.filter(x=>(x.name+' '+x.path).toLowerCase().includes(query.toLowerCase()));return breadcrumb('软件启动中心','从桌面和开始菜单识别常用软件，按用途分类，收藏后就能快捷启动。')+'<div class="toolbar">'+btn('◎ 扫描已安装软件','scan-apps','class="primary"')+'<input id="app-search" placeholder="搜索软件名称..." value="'+esc(query)+'"></div><div class="toolbar">'+kinds.map(k=>'<button type="button" data-act="app-kind" data-kind="'+k+'" class="'+(k===appKind?'primary':'')+'">'+k+'</button>').join('')+'</div><p class="muted">扫描的是 Windows 快捷方式，不代表每个子程序都需要收藏。推荐先按“工程设计 / 学习办公”筛选。</p><div class="cards">'+(xs.slice(0,180).map(x=>'<div class="card"><span class="pill">'+esc(x.kind)+'</span><h3>'+esc(x.name)+'</h3><p class="truncate">'+esc(x.path)+'</p><div class="actions">'+btn('▶ 启动','run-app','data-id="'+esc(x.id)+'" class="primary"')+btn(x.pinned?'★ 已收藏':'☆ 收藏','pin-app','data-id="'+esc(x.id)+'"')+'</div></div>').join('')||'<div class="empty card">没有符合条件的软件。先扫描开始菜单，或切换“全部”。</div>')+'</div>'}
function ai(){
 const options=Object.keys(profiles).map(x=>'<option '+(settings.provider===x?'selected':'')+'>'+esc(x)+'</option>').join('');
 return breadcrumb('NEXUS AI · 工程助手','聊天悬浮窗、项目上下文、多模型服务；发送截图和聊天历史必须由你主动确认。')+'<div class="columns chat-area"><section class="panel ai-settings float-hide"><h3>01 · 模型与接口</h3><div class="field"><label>服务平台</label><select id="provider">'+options+'</select></div><div class="field"><label>接口地址</label><input id="endpoint" value="'+esc(settings.endpoint||'')+'" spellcheck="false"></div><div class="field"><label>模型 ID</label><input id="model-id" value="'+esc(settings.model||'')+'" spellcheck="false"></div><div class="field"><label>API Key '+(settings.hasKey?'（已保存，可留空）':'（未配置）')+'</label><input id="api-key" type="password" placeholder="仅输入新密钥时才会覆盖原密钥" autocomplete="off"></div>'+btn('保存 AI 配置','settings-save','class="primary"')+btn('清除此平台密钥','clear-key')+'<p class="muted">密钥只存本机 Windows 加密存储。云端 AI 需要该平台的 API 额度。</p><h3>02 · 项目记忆</h3>'+btn('导入 ChatGPT conversations.json','history-import')+'<p class="muted">先从 ChatGPT 官方导出历史 JSON，本机索引。不会实时读取你的当前聊天。</p><div class="history-list">'+historyItems.slice(0,60).map(h=>'<div class="history-row"><span>'+esc(h.title)+'</span><select data-history="'+esc(h.id)+'"><option value="">未关联项目</option>'+projectOptions(h.projectId)+'</select></div>').join('')+'</div></section><section class="panel"><div class="row-between"><h3>✧ 与 AI 对话</h3><span class="pill">'+esc(settings.provider||'未设置')+' · '+esc(settings.model||'未选模型')+'</span></div><div class="field"><label>关联项目（可选）</label><select id="chat-project"><option value="">不关联项目</option>'+projectOptions(pid)+'</select></div><label class="inline-check"><input type="checkbox" id="include-history" '+(historyAllowed?'checked':'')+'> 允许本次消息包含本地历史项目摘录</label><div class="chat-log" id="chat-log" aria-live="polite">'+chatMessages.map(m=>'<div class="bubble '+(m.role==='user'?'user':m.role==='error'?'error':'')+'"><small>'+({'user':'我','assistant':'NEXUS AI','error':'请求失败'}[m.role])+'</small><div>'+esc(m.text)+'</div></div>').join('')+'</div><div id="chat-status" class="status">'+esc(activeError)+'</div><div id="image-box">'+(uploadImage?'<div class="image-preview"><img class="preview" id="screenshot-preview" src="'+esc(uploadImage)+'" alt="待发送截图">'+btn('移除截图','remove-image')+'<p class="muted">发送前请确认截图不包含私密信息。</p></div>':'')+'</div><textarea class="chat-input" id="chat-input" placeholder="例如：这个 Fluent 边界为什么为零？也可以粘贴 Win+Shift+S 的截图。">'+esc(chatDraft)+'</textarea><div class="toolbar">'+btn('截取屏幕','capture')+btn('清空对话','clear-chat')+btn(busy?'正在请求…':'发送问题','send-chat','class="primary" '+(busy?'disabled':''))+'</div><p class="muted">截图仅在你点击发送后上传至所选模型；不支持图片的模型请先切换。</p></section></div>';
}
function settingsPage(){return breadcrumb('设置与数据','所有数据保存在本机，工程源文件不会自动移动。')+'<div class="panel"><h3>应用设置</h3><p>当前客户端：PROJECT NEXUS · Electron 中文桌面版</p><p class="muted">F11 及右上角按钮可切换全屏。AI 悬浮窗口可置顶其他软件。</p>'+btn('AI 模型设置','navigate-ai')+'</div><div class="panel"><h3>数据与隐私</h3><p class="muted">工程映射仅存储本地路径；聊天导出必须由你主动选择；API Key 用 Windows 安全存储加密。请勿将私人聊天、截图、密钥上传到公开 GitHub 仓库。</p></div>'}
function render(){frame();$('section-title').textContent={home:'指挥中心',projects:'工程项目',files:'智能文件柜',work:'工作中心',apps:'软件启动台',ai:'NEXUS AI',settings:'设置与数据'}[page]||'指挥中心';$('content').innerHTML={home,projects,files,work,apps,ai,settings:settingsPage}[page]();if(page==='ai'){const box=$('chat-log');box.scrollTop=box.scrollHeight;const input=$('chat-input');input?.focus()}}
function setPage(x){page=x;render()}
function askProjectName(){return new Promise(resolve=>{const bg=document.createElement('div');bg.className='modal-overlay';bg.innerHTML='<div class="modal"><h2>创建新的项目抽屉</h2><p class="muted">支持科研、工程、课程与任何新工作。</p><input id="modal-name" maxlength="100" placeholder="例如：桥梁有限元分析"><div class="toolbar"><button id="modal-cancel">取消</button><button id="modal-ok" class="primary">确认创建</button></div></div>';document.body.appendChild(bg);const done=v=>{bg.remove();resolve(v)};bg.querySelector('#modal-cancel').onclick=()=>done('');bg.querySelector('#modal-ok').onclick=()=>done(bg.querySelector('#modal-name').value.trim());bg.querySelector('#modal-name').addEventListener('keydown',e=>{if(e.key==='Enter')done(e.target.value.trim());if(e.key==='Escape')done('')});bg.querySelector('#modal-name').focus()})}
async function refresh(){db=await api.load();if(!pid&&db.projects?.length)pid=db.projects[0].id;render()}
async function execute(fn){try{await fn()}catch(e){const error=safeErr(e);notify(error,'error');if(page==='ai'){activeError=error;chatMessages.push({role:'error',text:error});render()}console.error(e)}}
async function ask(prompt){const value=String(prompt||'').trim();if(!value||busy)return;busy=true;chatDraft=value;activeError='正在等待模型响应…';const recent=chatMessages.filter(m=>m.role==='user'||m.role==='assistant').slice(-8);chatMessages.push({role:'user',text:value});const payload={message:value,projectId:$('chat-project')?.value||'',includeHistory:historyAllowed,image:uploadImage||'',recent};uploadImage='';chatDraft='';render();try{const answer=await api.chat(payload);chatMessages.push({role:'assistant',text:answer});activeError='请求成功';}catch(e){activeError=safeErr(e);chatMessages.push({role:'error',text:activeError});}finally{busy=false;render()}}
document.addEventListener('input',e=>{if(e.target.id==='chat-input')chatDraft=e.target.value;if(e.target.id==='app-search'){query=e.target.value;const start=e.target.selectionStart;const end=e.target.selectionEnd;render();$('app-search')?.focus();$('app-search')?.setSelectionRange(start,end)}});
document.addEventListener('change',e=>{if(e.target.id==='include-history')historyAllowed=e.target.checked;if(e.target.id==='chat-project')pid=e.target.value;if(e.target.dataset.history){execute(async()=>{await api.assignHistory(e.target.dataset.history,e.target.value);historyItems=await api.listHistory();notify('历史记录已关联到项目，只有授权时才会发送摘要。')})}if(e.target.id==='provider'){const p=e.target.value;settings.provider=p;settings.endpoint=profiles[p]?.endpoint||'';settings.model=profiles[p]?.model||'';settings.hasKey=false;render()}if(e.target.dataset.act==='toggle-task')execute(async()=>{db=await api.toggleTask(e.target.dataset.id,e.target.dataset.task);render()});if(e.target.dataset.act==='toggle-work')execute(async()=>{db=await api.toggleWork(e.target.dataset.id);render()})});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.ctrlKey&&e.target.id==='chat-input'){e.preventDefault();execute(()=>ask(e.target.value))}if(e.key==='F11'){e.preventDefault();execute(()=>api.toggleFullscreen())}});
document.addEventListener('paste',e=>{if(page!=='ai')return;const item=[...(e.clipboardData?.items||[])].find(x=>x.type.startsWith('image/'));if(!item)return;e.preventDefault();const reader=new FileReader();reader.onload=()=>{uploadImage=String(reader.result);render();notify('已粘贴截图。发送前请确认隐私信息。')};reader.readAsDataURL(item.getAsFile())});
document.addEventListener('click',e=>{
 const el=e.target.closest('[data-act]');if(!el)return;const a=el.dataset.act,id=el.dataset.id;
 if(a==='nav'){setPage(id);return}if(a==='navigate-ai'){setPage('ai');return}
 execute(async()=>{
  switch(a){
   case 'fullscreen-toggle':await api.toggleFullscreen();return;
   case 'float-open':await api.openFloat();return;
   case 'create-project':{const name=await askProjectName();if(!name)return;db=await api.createProject(name,'自定义项目');pid=db.projects.at(-1)?.id;render();return}
   case 'select-project':selectProject(id);return;
   case 'open-project':await api.openProject(id);return;
   case 'pick-folder':db=await api.pickFolder(id);render();return;
   case 'pick-file':db=await api.pickFile(id);render();return;
   case 'remove-link':if(!confirm('确定只取消这个映射吗？源文件不会被删除。'))return;db=await api.removeLink(id,Number(el.dataset.index));render();return;
   case 'open-path':await api.openPath(el.dataset.path);return;
   case 'reveal':await api.revealPath(el.dataset.path);return;
   case 'add-task':{const title=$('new-task')?.value;if(!title?.trim())throw Error('请输入验收任务名称');db=await api.addTask(id,title);render();return}
   case 'create-work':{const title=$('work-title')?.value;if(!title?.trim())throw Error('请输入工作名称');db=await api.createWork(title);render();return}
   case 'add-root':db=await api.addRoot();render();return;
   case 'scan-apps':db=await api.scanApps();appKind='工程设计';render();notify('扫描完成：请按分类查看与收藏');return;
   case 'app-kind':appKind=el.dataset.kind;render();return;
   case 'pin-app':db=await api.pinApp(id);render();return;
   case 'run-app':await api.runApp(id);return;
   case 'settings-save':{const payload={provider:$('provider').value,endpoint:$('endpoint').value,model:$('model-id').value,key:$('api-key').value};settings=await api.saveSettings(payload);render();notify('模型设置已保存，可以发送“你好”测试。');return}
   case 'history-import':{const result=await api.importHistory();historyItems=await api.listHistory();render();notify('已导入 '+result.count+' 条历史会话摘要；请在下方指定所属项目。');return}case 'clear-key':{if(!confirm('确定清除当前 AI 平台保存的密钥？'))return;await api.clearKey();settings.hasKey=false;render();notify('当前平台密钥已清除');return}
   case 'send-chat':await ask($('chat-input')?.value||chatDraft);return;
   case 'capture':{const image=await api.capture();uploadImage=image;render();notify('截图已预览，只有点击发送才会上传');return}
   case 'remove-image':uploadImage='';render();return;
   case 'clear-chat':if(!confirm('清空当前窗口显示的对话？'))return;chatMessages=[];activeError='';render();return;
  }
 });
});
async function start(){try{profiles=await api.profiles();settings=await api.getSettings();db=await api.load();historyItems=await api.listHistory();if(isFloat){page='ai'}else if(db.projects?.length)pid=db.projects[0].id;render()}catch(e){$('root').textContent='NEXUS 初始化失败：'+safeErr(e);console.error(e)}}
start();
