import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {PATH,MARKERS,SCALE,pxToWorld,worldToPx} from './world.mjs';
import {makeRobot} from './robot-model.mjs';
const C={tire:0x131a20,wheel:0xf2bf37,ply:0xe4c899,edge:0x99642c,metal:0xbbd0d8,board:0x184f46,servo:0x164b8e};
const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.55,...extra});
function box(parent,w,h,d,m,x=0,y=0,z=0){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function cyl(parent,r,h,m,x=0,y=0,z=0,r2=r){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r2,h,24),m);mesh.position.set(x,y,z);mesh.castShadow=true;parent.add(mesh);return mesh;}
function trackCanvas(config){const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=1600;const ctx=canvas.getContext('2d');ctx.fillStyle='#77acd0';ctx.fillRect(0,0,1200,1600);ctx.strokeStyle='rgba(255,255,255,.08)';ctx.lineWidth=1;for(let x=0;x<1200;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,1600);ctx.stroke();}for(let y=0;y<1600;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1200,y);ctx.stroke();}
 function path(){ctx.beginPath();ctx.moveTo(190,1380);ctx.lineTo(190,485);ctx.arc(390,485,200,Math.PI,1.5*Math.PI);ctx.lineTo(790,285);ctx.arc(790,485,200,-Math.PI/2,0);ctx.lineTo(990,1253);ctx.arc(790,1253,200,0,Math.PI/2);ctx.lineTo(143,1453);}
 ctx.lineCap='butt';ctx.lineJoin='round';path();ctx.lineWidth=115;ctx.strokeStyle='#355269';ctx.stroke();path();ctx.lineWidth=112;ctx.strokeStyle='#f8fbfc';ctx.stroke();
 for(const [x,y,w,h,label] of [[519,342,140,140,'取物区'],[519,793,140,140,'停车区'],[381,1256,140,140,'放置区']]){ctx.fillStyle='#abd8e9';ctx.fillRect(x,y,w,h);ctx.strokeStyle='#49758a';ctx.lineWidth=2;ctx.strokeRect(x,y,w,h);ctx.fillStyle='#244d62';ctx.font='26px sans-serif';ctx.textAlign='center';ctx.fillText(label,x+w/2,y+h/2+9);}
 path();ctx.lineWidth=config.lineWidth/SCALE;ctx.strokeStyle='#11171c';ctx.stroke();for(const marker of MARKERS){ctx.beginPath();ctx.moveTo(...marker.a);ctx.lineTo(...marker.b);ctx.lineWidth=config.lineWidth/SCALE;ctx.stroke();}
 ctx.fillStyle='#176753';ctx.font='bold 24px sans-serif';ctx.textAlign='left';ctx.fillText('START',265,1300);ctx.beginPath();ctx.moveTo(273,1275);ctx.lineTo(289,1252);ctx.lineTo(305,1275);ctx.strokeStyle='#176753';ctx.lineWidth=5;ctx.stroke();
 ctx.fillStyle='#29455a';ctx.font='bold 20px sans-serif';ctx.fillText('FINISH',115,1550);ctx.fillStyle='#517f9b';ctx.font='18px sans-serif';ctx.fillText('参考赛道 · 比例可校准',710,1560);
 for(const [x,y,text] of [[93,510,'01'],[695,214,'02'],[1060,918,'03'],[1060,1233,'04'],[399,1535,'05']]){ctx.fillStyle='#274c64';ctx.font='bold 23px sans-serif';ctx.fillText(text,x,y);}
 return canvas;}
export class SceneView{
 constructor(host,world,onPlace){this.host=host;this.world=world;this.mode='overview';this.onPlace=onPlace;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x101c27);this.scene.fog=new THREE.Fog(0x101c27,11,28);this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.setClearColor(0x101c27);host.appendChild(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','可旋转缩放的赛道、小车及机械臂三维仿真');
 this.camera=new THREE.PerspectiveCamera(42,1,.01,60);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.maxDistance=13;this.controls.minDistance=.35;this.controls.maxPolarAngle=Math.PI/2-.05;this.controls.target.set(0,0,.1);
 this.scene.add(new THREE.HemisphereLight(0xd8eefa,0x435269,2.4));const sun=new THREE.DirectionalLight(0xfff6df,3.3);sun.position.set(-3,7,3);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-3,right:3,top:4,bottom:-4,near:.1,far:15});sun.shadow.bias=-.0003;this.scene.add(sun);
 const floor=box(this.scene,50,.03,50,mat(0x111e29),0,-.062,0);const grid=new THREE.GridHelper(30,150,0x304252,0x20303e);grid.position.y=-.043;this.scene.add(grid);
 const tex=new THREE.CanvasTexture(trackCanvas(world.config));tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=8;this.mapTexture=tex;const center=pxToWorld(600,800);this.board=box(this.scene,3.6,.03,4.8,mat(0x557a98),center.x,-.025,center.z);this.track=new THREE.Mesh(new THREE.PlaneGeometry(3.6,4.8),new THREE.MeshStandardMaterial({map:tex,roughness:.93}));this.track.rotation.x=-Math.PI/2;this.track.position.set(center.x,-.008,center.z);this.track.receiveShadow=true;this.scene.add(this.track);
 this.robot=makeRobot(world.config);this.scene.add(this.robot.root);this.rays=new THREE.Group();this.scene.add(this.rays);this.sensorDots=Array.from({length:4},()=>{const dot=new THREE.Mesh(new THREE.CylinderGeometry(.012,.012,.003,16),new THREE.MeshBasicMaterial({color:0x64e0cd}));this.scene.add(dot);return dot;});
 this.trailGeo=new THREE.BufferGeometry();this.trailLine=new THREE.Line(this.trailGeo,new THREE.LineBasicMaterial({color:0xefb744,transparent:true,opacity:.8}));this.scene.add(this.trailLine);
 this.insetCamera=new THREE.PerspectiveCamera(39,1,.01,15);this.setView('overview');this.resize=new ResizeObserver(()=>this.resizeToHost());this.resize.observe(host);this.resizeToHost();this.raycaster=new THREE.Raycaster();this.pointerDown=e=>{this.down={x:e.clientX,y:e.clientY};};this.pointerUp=e=>{if(!this.placing||!this.down||Math.hypot(e.clientX-this.down.x,e.clientY-this.down.y)>8)return;const r=this.renderer.domElement.getBoundingClientRect();this.raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),this.camera);const hits=this.raycaster.intersectObject(this.track);if(hits[0])this.onPlace({x:hits[0].point.x,z:hits[0].point.z});};this.renderer.domElement.addEventListener('pointerdown',this.pointerDown);this.renderer.domElement.addEventListener('pointerup',this.pointerUp);this.lastAngles=[];this.updateArm();}
 resizeToHost(){const w=this.host.clientWidth,h=this.host.clientHeight;if(w&&h){this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}}
 setView(mode){this.mode=mode;const p=this.world.pose;this.camera.up.set(0,1,0);if(mode==='top'){this.camera.position.set(0,7.4,.001);this.controls.target.set(0,0,0);this.controls.enableRotate=false;this.controls.mouseButtons.LEFT=THREE.MOUSE.PAN;}else if(mode==='arm'){this.camera.position.set(p.x-Math.sin(p.theta)*.65+Math.cos(p.theta)*.7,.57,p.z+Math.cos(p.theta)*.65+Math.sin(p.theta)*.7);this.controls.target.set(p.x,.27,p.z);this.controls.enableRotate=true;this.controls.mouseButtons.LEFT=THREE.MOUSE.ROTATE;}else if(mode==='follow'){this.camera.position.set(p.x-Math.cos(p.theta)*.85,.7,p.z-Math.sin(p.theta)*.85);this.controls.target.set(p.x,.12,p.z);this.controls.enableRotate=true;this.controls.mouseButtons.LEFT=THREE.MOUSE.ROTATE;}else{this.camera.position.set(3.1,5.8,4.25);this.controls.target.set(0,0,.15);this.controls.enableRotate=true;this.controls.mouseButtons.LEFT=THREE.MOUSE.ROTATE;}this.controls.update();}
 setPlace(value){this.placing=value;this.renderer.domElement.style.cursor=value?'crosshair':'grab';}
 refreshTrack(){const old=this.mapTexture;this.mapTexture=new THREE.CanvasTexture(trackCanvas(this.world.config));this.mapTexture.colorSpace=THREE.SRGBColorSpace;this.mapTexture.anisotropy=8;this.track.material.map=this.mapTexture;this.track.material.needsUpdate=true;old.dispose();}
 updateArm(){const angles=this.world.angles;if(angles.every((v,i)=>Math.abs(v-(this.lastAngles[i]??-999))<.08)&&this.armConfig===JSON.stringify(this.world.config))return;this.lastAngles=[...angles];this.armConfig=JSON.stringify(this.world.config);this.robot.mearm.update(angles,this.world.config);}
 render(){const world=this.world,p=world.pose,robot=this.robot;robot.root.position.set(p.x,0,p.z);robot.root.rotation.y=-p.theta-Math.PI/2;robot.wheels.forEach((w,i)=>{w.rotation.x=world.wheelAngles[i];w.position.x=(i<2?-1:1)*(world.config.wheelbase/2+.012);});robot.sensorBar.position.z=-world.config.sensorForward;robot.sensorMounts.position.z=.17-world.config.sensorForward;robot.sensorBar.scale.x=world.config.sensorSpacing*4/.115;world.sensorPositions.forEach((pos,i)=>{this.sensorDots[i].visible=world.config.showSensors;this.sensorDots[i].position.set(pos.x,.001,pos.z);this.sensorDots[i].material.color.setHex(world.sensors[i]===(world.config.blackHigh?1:0)?0xffb449:0x64e0cd);const j=world.config.reverseSensors?3-i:i;robot.sensors[i].position.set((j-1.5)*world.config.sensorSpacing,.037,-world.config.sensorForward);robot.sensors[i].userData.status.material.color.setHex(world.sensors[i]===(world.config.blackHigh?1:0)?0xffb449:0x64e0cd);});this.updateArm();
 if(this.mode==='follow'){const desired=new THREE.Vector3(p.x-Math.cos(p.theta)*.85,.7,p.z-Math.sin(p.theta)*.85);this.camera.position.lerp(desired,.09);this.controls.target.lerp(new THREE.Vector3(p.x,.17,p.z),.2);}else if(this.mode==='arm'){const delta=new THREE.Vector3(p.x,.27,p.z).sub(this.controls.target);this.camera.position.add(delta);this.controls.target.add(delta);}
 this.trailLine.visible=world.config.showTrail;if(world.trail.at(-1)!==this.lastTrailPoint){this.trailGeo.setFromPoints(world.trail.map(q=>new THREE.Vector3(q.x,.006,q.z)));this.lastTrailPoint=world.trail.at(-1);}
 this.controls.update();const w=this.host.clientWidth,h=this.host.clientHeight;this.renderer.setScissorTest(false);this.renderer.setViewport(0,0,w,h);this.renderer.render(this.scene,this.camera);
 if(this.mode!=='arm'&&w>480){const iw=Math.min(215,w*.28),ih=iw*.85;const label=this.host.querySelector('.inset-label');if(label)label.style.bottom=(ih+1)+'px';this.insetCamera.aspect=iw/ih;this.insetCamera.position.set(p.x-Math.sin(p.theta)*.59+Math.cos(p.theta)*.66,.53,p.z+Math.cos(p.theta)*.59+Math.sin(p.theta)*.66);this.insetCamera.lookAt(p.x,.26,p.z);this.insetCamera.updateProjectionMatrix();this.renderer.setScissorTest(true);this.renderer.setScissor(15,15,iw,ih);this.renderer.setViewport(15,15,iw,ih);this.renderer.clearDepth();this.renderer.render(this.scene,this.insetCamera);this.renderer.setScissorTest(false);}}
 dispose(){this.resize.disconnect();this.controls.dispose();this.renderer.domElement.removeEventListener('pointerdown',this.pointerDown);this.renderer.domElement.removeEventListener('pointerup',this.pointerUp);this.scene.traverse(o=>{o.geometry?.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose();});this.mapTexture.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
}
