'use client';
import {useEffect,useRef,useState} from 'react';
import {Play,Pause,RotateCcw,StepForward,Code2,Activity,SlidersHorizontal,Box,ScanLine,Focus,Cpu,Download,Upload,Info,LocateFixed,Terminal,ArrowUpRight,Check,AlertTriangle,Square,MousePointer2,RotateCw,ChevronRight,Radio,Armchair,Workflow,FileCode2,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Switch} from '@/components/ui/switch';
import CodeEditor from './CodeEditor';
import {Simulation,DEFAULT_CONFIG,START} from '@/lib/sim/world.mjs';
const EMPTY_PROGRAMS={line:'',arm:'',combined:''};
const LABELS={line:'循迹程序',arm:'机械臂程序',combined:'融合程序'};
const SERVO_NAMES=['zhuan · 底座','left · 大臂','right · 小臂','zhua · 夹爪'];
type Program=keyof typeof LABELS;
const initial={time:0,running:false,pose:START,sensors:[0,1,1,0],motor:[0,0,0,0],targets:[90,90,90,140],angles:[90,90,90,140],variables:{},line:0,delay:0,loops:0,crossings:0,distance:0,velocity:0,finished:false,error:null,logs:[]};
function Choice({value,onChange,options,label}:{value:string,onChange:(v:string)=>void,options:[string,string][],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,n])=><SelectItem key={v} value={v}>{n}</SelectItem>)}</SelectContent></Select>}
function NumberInput({value,onChange,min,max,step=1,label}:{value:number,onChange:(v:number)=>void,min?:number,max?:number,step?:number,label:string}){return <input className="number-input" type="number" aria-label={label} value={Number(value.toFixed(3))} min={min} max={max} step={step} onChange={e=>{if(e.target.value==='')return;const v=Number(e.target.value);if(Number.isFinite(v))onChange(Math.max(min??-Infinity,Math.min(max??Infinity,v)));}}/>}
export default function Lab(){
 const [program,setProgram]=useState<Program>('line'),[drafts,setDrafts]=useState<Record<Program,string>>({...EMPTY_PROGRAMS}),[snap,setSnap]=useState<any>(initial),[camera,setCamera]=useState('overview'),[speed,setSpeed]=useState('1'),[manual,setManual]=useState(false),[manualValues,setManualValues]=useState([0,1,1,0]),[dirty,setDirty]=useState(false),[dialog,setDialog]=useState<string|null>(null),[config,setConfig]=useState<any>(structuredClone(DEFAULT_CONFIG)),[viewError,setViewError]=useState(''),[placing,setPlacing]=useState(false),[notice,setNotice]=useState('请输入或导入你的 Arduino 代码，再点击「编译并运行」。小车初始灰度读数为 0 1 1 0。'),[errorLine,setErrorLine]=useState(0),[localReady,setLocalReady]=useState(false),[resetConfirm,setResetConfirm]=useState(false),[tab,setTab]=useState('telemetry');
 const host=useRef<HTMLDivElement>(null),sim=useRef<any>(null),scene=useRef<any>(null),speedRef=useRef(1),jump=useRef<(line:number)=>void>(()=>{}),file=useRef<HTMLInputElement>(null),programRef=useRef<Program>('line'),draftsRef=useRef(drafts),runRef=useRef<()=>void>(()=>{});draftsRef.current=drafts;programRef.current=program;
 const refresh=()=>{if(sim.current)setSnap(sim.current.snapshot());};
 useEffect(()=>{const world=new Simulation();sim.current=world;let saved:any=null;try{saved=JSON.parse(localStorage.getItem('linearm-code-drafts-v2-empty')??'null');if(saved&&Object.keys(LABELS).every(k=>typeof saved[k]==='string'&&saved[k].length<90000)){setDrafts(saved);if(saved.line.trim()){world.load(saved.line);setNotice('已恢复你在本浏览器输入的代码草稿。');}}}catch{}setLocalReady(true);refresh();let frame=0,disposed=false,last=performance.now(),lastUi=0;import('@/lib/sim/scene.mjs').then(({SceneView})=>{if(disposed||!host.current)return;try{scene.current=new SceneView(host.current,world,(pose:any)=>{world.running=false;world.moveTo(pose);setPlacing(false);scene.current.setPlace(false);refresh();});}catch(e){setViewError('此设备未能启用三维显示。代码和实时数据仍可运行，请使用支持 WebGL 的浏览器。');}}).catch(()=>setViewError('三维资源加载失败，请刷新页面重试。'));
 const loop=(now:number)=>{const elapsed=Math.min(now-last,40);last=now;if(world.running)world.tick(elapsed*speedRef.current);scene.current?.render();if(now-lastUi>90){setSnap(world.snapshot());lastUi=now;}frame=requestAnimationFrame(loop);};frame=requestAnimationFrame(loop);const visibility=()=>{if(document.hidden){world.running=false;refresh();}};document.addEventListener('visibilitychange',visibility);return()=>{disposed=true;cancelAnimationFrame(frame);scene.current?.dispose();scene.current=null;document.removeEventListener('visibilitychange',visibility);};},[]);
 useEffect(()=>{if(localReady){try{localStorage.setItem('linearm-code-drafts-v2-empty',JSON.stringify(drafts));}catch{setNotice('浏览器无法保存草稿，请导出代码备份。');}}},[drafts,localReady]);
 const run=()=>{const w=sim.current;if(!w)return;if(!draftsRef.current[programRef.current].trim()){w.source='';w.reset();setDirty(false);setErrorLine(0);setNotice('代码还是空白，请先输入或导入你的程序。');refresh();return;}try{w.load(draftsRef.current[programRef.current]);w.running=true;setDirty(false);setErrorLine(0);setNotice('正在执行当前代码。修改后重新运行将从 setup() 开始。');refresh();}catch(e:any){w.running=false;w.error=e;w.log('error',e.message);setErrorLine(e.line??0);setNotice(e.message);refresh();}};runRef.current=run;
 const updateCode=(value:string)=>{if(value===draftsRef.current[programRef.current])return;setDrafts(prev=>({...prev,[programRef.current]:value}));if(sim.current){sim.current.running=false;setDirty(sim.current.source!==value);}setNotice('代码已修改，点击「编译并运行」应用。');setErrorLine(0);refresh();};
 const switchProgram=(p:Program)=>{setProgram(p);programRef.current=p;const w=sim.current;if(w){w.running=false;w.error=null;try{if(draftsRef.current[p].trim())w.load(draftsRef.current[p]);else{w.source='';w.reset();}setDirty(false);setErrorLine(0);}catch(e:any){w.error=e;setErrorLine(e.line??0);setDirty(true);}refresh();}const cam=p==='arm'?'arm':'overview';setCamera(cam);scene.current?.setView(cam);setNotice(draftsRef.current[p].trim()?'已切换到你的程序，点击编译并运行。':p==='combined'?'请写入你的融合程序，整份代码保留一个 setup() 和一个 loop()。':'请在空白编辑器中输入或导入你的程序。');};
 const reset=()=>{const w=sim.current;if(!w)return;w.reset();setErrorLine(0);setNotice('已复位到设定起点，变量、输出和仿真时间已清零。');refresh();};
 const pause=()=>{const w=sim.current;if(!w)return;if(dirty||!w.vm){run();return;}if(w.error)return;w.running=!w.running;refresh();};
 const step=()=>{const w=sim.current;if(!w)return;if(!draftsRef.current[programRef.current].trim()){setNotice('请先输入你的程序，再使用单步运行。');return;}if(dirty||!w.vm){try{w.load(draftsRef.current[programRef.current]);setDirty(false);}catch(e:any){w.error=e;setErrorLine(e.line??0);refresh();return;}}w.running=false;w.tick(20);refresh();};
 const setCfg=(key:string,value:any)=>{const next={...config,[key]:value};setConfig(next);if(sim.current){sim.current.running=false;sim.current.config=next;sim.current.sample();if(key==='lineWidth')scene.current?.refreshTrack();refresh();}};
 const placePreset=(kind:string)=>{const w=sim.current;if(!w)return;w.running=false;w.manualSensors=null;setManual(false);if(kind==='start')w.moveTo({...START});if(kind==='marker')w.moveTo({x:(190-580)*.003,z:(540-850)*.003+config.sensorForward,theta:-Math.PI/2});if(kind==='finish')w.moveTo({x:(300-580)*.003,z:(1453-850)*.003,theta:Math.PI});w.reset();refresh();setNotice(kind==='start'?'已回到黑线中心，恢复赛道自动采样。当前 S1–S4：'+w.sensors.join(' ')+'。':'位置已更新，当前 S1–S4：'+w.sensors.join(' ')+'，下次运行从此位置开始。');};
 const download=()=>{const blob=new Blob([drafts[program]],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${program}-esp32.ino`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const importFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f){if(f.size>90000){setNotice('文件太大，请使用 90 KB 以内的 Arduino 程序。');}else{updateCode(await f.text());setNotice(`已导入 ${f.name}，点击编译并运行。`);}}e.target.value='';};
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();const register=(tool:any)=>{try{Promise.resolve(ctx.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};
 register({name:'read_simulation_state',title:'读取仿真状态',description:'读取时间、传感器、电机、舵机及程序错误。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>sim.current?.snapshot()??{ready:false}});
 register({name:'stage_arduino_code',title:'载入 Arduino 代码草稿',description:'替换当前编辑器草稿并暂停；需要再运行才能执行。',inputSchema:{type:'object',properties:{code:{type:'string',maxLength:90000}},required:['code'],additionalProperties:false},execute:(input:any)=>{if(typeof input?.code!=='string'||input.code.length>90000)throw new Error('需要有效的代码文本');updateCode(input.code);return{staged:true,running:false};}});
 register({name:'control_simulation',title:'运行或暂停仿真',description:'run 编译并从起点运行当前草稿；pause 暂停；reset 复位。',inputSchema:{type:'object',properties:{action:{type:'string',enum:['run','pause','reset']}},required:['action'],additionalProperties:false},execute:(input:any)=>{if(!['run','pause','reset'].includes(input?.action))throw new Error('未知操作');if(input.action==='run')runRef.current();else if(input.action==='pause')sim.current.running=false;else sim.current.reset();refresh();return sim.current.snapshot();}});return()=>life.abort();},[]);
 const blackBits=snap.sensors.map((n:number)=>n===(config.blackHigh?1:0)?1:0).join('');
 const sensorMode=manual?'手动注入':blackBits==='0110'?'居中 · 中间两路黑':blackBits==='0000'?'全白 / 丢线':blackBits==='1111'?'交叉线 · 四路全黑':'循迹 · 偏离中线';
 return <main className="lab dark">
 <header className="app-header"><div className="brand-mark"><Workflow size={23}/></div><div className="brand"><strong>LINE / ARM<span>SIMULATOR</span></strong><h1>循迹与机械臂实验台</h1></div><div className="header-divider"/><div className="hardware-tag"><Cpu size={16}/> ESP32 <span>×</span> MeArm</div><div className="header-actions"><button className="text-button" onClick={()=>setDialog('reference')}><Box size={16}/><span>实物与赛道</span></button><button className="icon-button" onClick={()=>setDialog('help')} aria-label="使用说明与支持范围"><Info size={19}/></button></div></header>
 <div className="command-bar"><div className="command-title"><span className="eyebrow">EXPERIMENT 01</span><h2>从代码，到动作。</h2></div><div className="run-controls"><button className="primary-button" onClick={run}><Play size={17} fill="currentColor"/>编译并运行</button><button className="control-button" onClick={pause} disabled={!!snap.error} aria-label={snap.running?'暂停仿真':'继续仿真'}>{snap.running?<Pause size={17}/>:<Play size={17}/>}<span>{snap.running?'暂停':'继续'}</span></button><button className="icon-button" title="暂停后推进 20 毫秒" aria-label="推进 20 毫秒" onClick={step}><StepForward size={19}/></button><button className="icon-button" title="复位" aria-label="复位仿真" onClick={reset}><RotateCcw size={18}/></button><span className="control-divider"/><Choice value={speed} label="仿真速度" onChange={v=>{setSpeed(v);speedRef.current=Number(v);}} options={[["0.25","0.25×"],["0.5","0.5×"],["1","1× 速度"],["2","2×"],["4","4×"]]}/></div><div className="runtime-clock"><span className={'runtime-state '+(snap.running?'running':snap.error?'error':'')}>{snap.error?'执行错误':dirty?'待应用':snap.running?'运行中':!drafts[program].trim()?'待输入代码':'已暂停'}</span><b>{(snap.time/1000).toFixed(2)}<small>s</small></b></div></div>
 <div className="workspace"><section className="viewport-panel"><div className="panel-top"><div className="panel-title"><Box size={16}/><span>仿真场景</span><span className="muted-meta">参考赛道</span></div><div className="camera-buttons">{[['overview','三维',Box],['top','俯视',ScanLine],['follow','随车',Focus],['arm','机械臂',Activity]].map(([key,label,Icon]:any)=><button key={key} className={camera===key?'selected':''} onClick={()=>{setCamera(key);scene.current?.setView(key);}}><Icon size={14}/><span>{label}</span></button>)}</div></div>
 <div className="scene" ref={host}>{viewError&&<div className="scene-error"><AlertTriangle/><p>{viewError}</p></div>}<div className="scene-label"><span className="scene-id">TRACK — 01</span><span>四轮差速 · 四路灰度</span></div><div className="scene-tags"><span className={manual?'warn':''}><Radio size={12}/>{manual?'手动传感器输入':'实时赛道采样'}</span>{snap.finished&&<span className="warn">已通过终点</span>}</div><div className="scene-sensor-readout" aria-label="当前传感器实际采样"><span>{sensorMode}</span><div>{snap.sensors.map((v:number,i:number)=><div key={i} className={v===(config.blackHigh?1:0)?'on-black':'on-white'}><small>S{i+1}</small><b>{v}</b></div>)}</div></div><div className="scene-navigation"><button className={placing?'active':''} aria-label="点击赛道放置小车" title="点击赛道设置小车位置" onClick={()=>{const value=!placing;setPlacing(value);scene.current?.setPlace(value);if(sim.current)sim.current.running=false;refresh();}}><MousePointer2 size={18}/></button><button aria-label="恢复当前视角" title="恢复当前视角" onClick={()=>scene.current?.setView(camera)}><Focus size={18}/></button></div><div className="scene-help">{placing?'点击赛道放置小车；方向可在参数中调整':camera==='top'?'滚轮缩放 · 拖动平移':'拖动旋转 · 滚轮缩放 · 双指操作'}</div>{camera!=='arm'&&<div className="inset-label">ROBOT CAM</div>}<div className="axis-label"><span>X</span><b>Y ↑</b><span>Z</span></div></div>
 <div className="scene-footer"><span><i className="legend-dot amber"/>黑线 = {config.blackHigh?1:0}</span><span><i className="legend-dot mint"/>白底 = {config.blackHigh?0:1}</span><span className="scene-footer-note">左侧起步 · 左下竖线终点</span><button className="text-button centered-start" onClick={()=>placePreset('start')} title="回到黑线中心并恢复真实赛道采样"><LocateFixed size={14}/>居中起点</button><button className="text-button" onClick={()=>setDialog('config')}><SlidersHorizontal size={14}/>校准参数</button></div></section>
 <section className="code-panel"><div className="panel-top"><div className="panel-title"><Code2 size={17}/><span>程序编辑器</span></div><span className="file-type">ARDUINO C++</span></div><Tabs value={program} onValueChange={v=>switchProgram(v as Program)} className="code-tabs"><TabsList variant="line">{Object.entries(LABELS).map(([k,v])=><TabsTrigger key={k} value={k}>{v}{k===program&&dirty&&<i className="draft-dot"/>}</TabsTrigger>)}</TabsList></Tabs><div className="code-filebar"><span><FileCode2 size={14}/>{program}.ino</span><div><button title="导入 .ino 代码" aria-label="导入代码" onClick={()=>file.current?.click()}><Upload size={15}/></button><button title="导出当前代码" aria-label="导出当前代码" onClick={download}><Download size={15}/></button><button title="清空当前代码" aria-label="清空当前代码" onClick={()=>setResetConfirm(true)}><RotateCcw size={14}/></button></div><input ref={file} hidden type="file" accept=".ino,.txt,.cpp,.h" onChange={importFile}/></div>
 <CodeEditor value={drafts[program]} onChange={updateCode} line={dirty?0:(errorLine||snap.line)} onRun={()=>runRef.current()} onReady={fn=>jump.current=fn}/>
 <div className={'code-status '+(snap.error?'has-error':'')}><span>{snap.error?<AlertTriangle size={14}/>:dirty?<Square size={12}/>:<Check size={14}/>}</span><span>{snap.error?'执行失败':dirty?'草稿待运行':!drafts[program].trim()?'空白程序 · 等待输入':'编辑后重新运行生效'}</span><button onClick={()=>jump.current(errorLine||snap.line||1)}>L{errorLine||snap.line||1}<LocateFixed size={13}/></button></div><div className="editor-hint">Ctrl / ⌘ + Enter 运行<span>草稿保存在本浏览器</span></div></section></div>
 <div className={'message-strip '+(snap.error?'error-strip':'')} role="status"><span>{snap.error?<AlertTriangle size={16}/>:<Terminal size={16}/>}</span><p>{snap.error??notice}</p>{snap.delay>0&&<b>delay · 剩余 {Math.ceil(snap.delay)} ms</b>}</div>
 <section className="instruments"><Tabs value={tab} onValueChange={setTab}><div className="instruments-heading"><TabsList variant="line"><TabsTrigger value="telemetry"><Activity size={15}/>实时数据</TabsTrigger><TabsTrigger value="log"><Terminal size={15}/>串口与事件</TabsTrigger></TabsList><div className="metrics-mini"><span>里程 <b>{snap.distance.toFixed(2)} m</b></span><span>全黑进入 <b>{snap.crossings}</b></span><span>变量 i <b>{snap.variables.i??'—'}</b></span></div></div>
 <TabsContent value="telemetry"><div className="telemetry-grid"><div className="instrument sensors"><div className="instrument-title"><h3>灰度传感器</h3><span className={manual?'status-warning':''}>{sensorMode}</span></div><div className="sensor-row">{snap.sensors.map((v:number,i:number)=><button className={'sensor-chip '+(v?'high':'low')} key={i} disabled={!manual} onClick={()=>{const next=[...manualValues];next[i]=1-next[i];setManualValues(next);if(sim.current){sim.current.manualSensors=next;sim.current.sample();refresh();}}} aria-label={`S${i+1} 当前为 ${v}${manual?'，点击切换':''}`}><span>S{i+1}<small>GPIO {config.sensorPins[i]}</small></span><b>{v}</b><i/></button>)}</div><div className="instrument-foot"><span>S1 至 S4 · 从左到右</span><label><Switch checked={manual} aria-label="手动注入灰度读数" onCheckedChange={v=>{setManual(v);if(sim.current){sim.current.manualSensors=v?[...manualValues]:null;sim.current.sample();refresh();}}}/>注入读数</label></div>{manual&&<div className="sensor-presets">{['0110','0011','1111','0000'].map(bits=><button key={bits} onClick={()=>{const v=bits.split('').map(Number);setManualValues(v);sim.current.manualSensors=v;sim.current.sample();refresh();}}>{bits}</button>)}</div>}</div>
 <div className="instrument motors"><div className="instrument-title"><h3>电机输出</h3><span>PWM · −255 ~ 255</span></div><div className="motor-grid">{snap.motor.map((v:number,i:number)=><div key={i} className="motor-item"><span>M{i+1}<small>{config.motorSides[i]==='left'?'左侧':'右侧'}</small></span><div className="motor-meter"><div style={{width:`${Math.abs(v)/255*100}%`}} className={v<0?'reverse':''}/></div><b>{v}</b></div>)}</div><div className="instrument-foot"><span>当前车速</span><b>{(snap.velocity*100).toFixed(1)} cm/s</b></div></div>
 <div className="instrument servos"><div className="instrument-title"><h3>MeArm 舵机</h3><span>实际 / 目标角度</span></div><div className="servo-grid">{snap.targets.map((v:number,i:number)=><div key={i}><span>{SERVO_NAMES[i]}</span><p><b>{Math.round(snap.angles[i])}°</b><small>/ {Math.round(v)}°</small></p><div className="servo-meter"><i style={{width:`${snap.angles[i]/180*100}%`}}/></div></div>)}</div><div className="instrument-foot"><span>GPIO {config.servoPins.join(' / ')}</span><button className="text-button" onClick={()=>{setCamera('arm');scene.current?.setView('arm');}}>查看机械臂<Focus size={13}/></button></div></div></div></TabsContent>
 <TabsContent value="log"><div className="log-panel">{snap.logs.length?snap.logs.map((l:any,i:number)=><div className={'log-row '+l.type} key={i}><span>{(l.time/1000).toFixed(3)}s</span><b>{l.type==='serial'?'SERIAL':l.type==='error'?'ERROR':l.type==='marker'?'SENSOR':'SYSTEM'}</b><p>{l.text}</p></div>):<p className="empty-log">运行程序后显示事件；可在代码中使用 Serial.println() 输出调试信息。</p>}<div className="variables-row">全局变量：{Object.entries(snap.variables).map(([k,v])=><code key={k}>{k} = {String(v)}</code>)}<span>loop() 已执行 {snap.loops} 次</span></div></div></TabsContent></Tabs></section>
 <footer className="page-footer"><span>Arduino 逻辑与运动学仿真 · 模型尺寸及方向可校准</span><button onClick={()=>setDialog('help')}>支持范围与使用说明<Info size={13}/></button></footer>
 <Dialog open={dialog==='reference'} onOpenChange={v=>!v&&setDialog(null)}><DialogContent className="wide-dialog"><DialogTitle>你的赛道与实物</DialogTitle><DialogDescription>依据你提供的图片重建。默认左侧直道向上出发，左下竖线为终点；起点位置和朝向可调整。</DialogDescription><div className="reference-grid"><img src="./references/track.png" alt="用户提供的比赛赛道，左侧起点及左下终点"/><div><img src="./references/robot-side.jpeg" alt="用户实物侧视：加长双层透明车身、黄色轮毂和后置木质 MeArm"/><p>按实物照片调整为加长双层透明底盘、黄色五辐轮毂、前置灰度板及后置木质 MeArm，补充三角连接板、辅助连杆和齿轮夹爪。照片无法确定精确尺寸，模型比例和舵机零位仍需实测校准。</p><img src="./references/mearm.jpg" alt="用于核对三角连接板、平行连杆及夹爪结构的 MeArm 参考照片"/><button onClick={()=>setDialog('config')}><SlidersHorizontal size={16}/>调整模型参数</button></div></div></DialogContent></Dialog>
 <Dialog open={dialog==='help'} onOpenChange={v=>!v&&setDialog(null)}><DialogContent className="wide-dialog help-dialog"><DialogTitle>让你自己的代码驱动仿真</DialogTitle><DialogDescription>直接编辑或导入 .ino；点击「编译并运行」后从 setup() 开始。修改代码会暂停当前仿真。</DialogDescription><div className="help-grid"><div><h3>自己编写三份程序</h3><p>三个代码页初次打开均为空白，由你输入或导入自己的程序。循迹页和机械臂页可分别调试，融合页可写入同一 ESP32 控制底盘与机械臂的完整代码。之后会保存你在本浏览器输入的草稿。</p><h3>按代码执行的行为</h3><ul><li>同一时刻只运行当前页的一份程序。</li><li>只有一个 setup() 和一个 loop()；重复定义会报错。</li><li>delay() 阻塞程序执行，电机输出持续、舵机继续运动。</li><li>for 循环中没有 delay() 时，会快速写入最终角度；不会人为变成慢扫。</li><li>没有命中条件分支时，保持之前的引脚输出。</li><li>到达终点不会自动停车，要由你的代码发出停车命令。</li></ul></div><div><h3>已接通的语法与接口</h3><p>int / float / bool、全局变量、数组、函数、if / else、for / while / do、return、break / continue、算术与逻辑运算、#define。</p><p>pinMode、digitalRead / digitalWrite、analogWrite、delay / millis / micros、Serial.print / println、Servo.attach / write / writeMicroseconds / read / detach、常用数学函数。</p><h3>仿真边界</h3><p>这是 Arduino C++ 子集解释器和运动学模型，并非完整 ESP32 芯片或电路仿真。不支持的第三方库、指针、类、FreeRTOS、网络和中断会明确报错。普通 loop 按约 1 ms 调度，非指令周期精度。</p><p>理想地面采样；analogRead 仅返回 0 或 4095。轮胎打滑、惯性、电机负载、电气干扰与 PWM 资源冲突未建模。MeArm 的平行连杆共用关节点，角度到连杆姿态仍采用可校准近似，抓取为距离阈值模型；不能代替实物验证。</p></div></div><div className="help-note">模型不会自动循迹或自动播放机械臂动作。每次运行都执行你当前页的代码；停止、转向和抓取时机由代码决定。</div><div className="doc-links"><a href="https://docs.espressif.com/projects/arduino-esp32/en/latest/api/ledc.html" target="_blank" rel="noreferrer">Arduino ESP32 接口文档</a><a href="https://github.com/madhephaestus/ESP32Servo" target="_blank" rel="noreferrer">ESP32Servo 接口说明</a></div></DialogContent></Dialog>
 <Dialog open={dialog==='config'} onOpenChange={v=>!v&&setDialog(null)}><DialogContent className="wide-dialog config-dialog"><DialogTitle>模型与接线参数</DialogTitle><DialogDescription>这些参数定义实物连接和近似尺寸；程序只能通过对应 GPIO 控制硬件。更改参数会暂停运行。</DialogDescription><Tabs defaultValue="geometry"><TabsList><TabsTrigger value="geometry">赛道与底盘</TabsTrigger><TabsTrigger value="wiring">GPIO 接线</TabsTrigger><TabsTrigger value="arm">机械臂校准</TabsTrigger></TabsList><TabsContent value="geometry"><div className="config-grid">{[['maxSpeed','满 PWM 车速','cm/s',100,10,150],['wheelbase','左右轮距','cm',100,10,45],['sensorSpacing','传感器间距','mm',1000,10,55],['sensorForward','传感器前伸','cm',100,5,30],['lineWidth','黑线宽度','mm',1000,10,80]].map(([k,n,u,f,min,max]:any)=><div className="range-row" key={k}><label>{n}<span>{(config[k]*f).toFixed(0)} {u}</span></label><Slider value={[config[k]*f]} min={min} max={max} step={1} onValueChange={v=>setCfg(k,v[0]/f)} aria-label={n}/></div>)}<div className="switch-row"><label>黑线输出高电平</label><Switch checked={config.blackHigh} onCheckedChange={v=>setCfg('blackHigh',v)} aria-label="黑线输出高电平"/></div><div className="switch-row"><label>反转 S1–S4 排列</label><Switch checked={config.reverseSensors} onCheckedChange={v=>setCfg('reverseSensors',v)} aria-label="反转传感器排列"/></div><div className="switch-row"><label>显示行驶轨迹</label><Switch checked={config.showTrail} onCheckedChange={v=>setCfg('showTrail',v)} aria-label="显示轨迹"/></div></div><div className="pose-config"><h3>起点位置</h3><div className="pose-buttons"><button onClick={()=>placePreset('start')}>左侧起点</button><button onClick={()=>placePreset('marker')}>首个全黑标记</button><button onClick={()=>placePreset('finish')}>终点前方</button></div><div className="pose-fields">{[['x','X / cm',100],['z','Z / cm',100],['theta','朝向 / °',180/Math.PI]].map(([k,n,f]:any)=><label key={k}>{n}<NumberInput label={n} value={snap.pose[k]*f} min={k==='theta'?-360:-400} max={k==='theta'?360:400} onChange={v=>{sim.current.moveTo({[k]:v/f});refresh();}}/></label>)}</div><p>朝向 0° 向右，−90° 向上；位置坐标以赛道图中的中心附近为原点。也可关闭面板后点击场景定位按钮放置小车。</p></div></TabsContent>
 <TabsContent value="wiring"><div className="wiring-table"><div className="wiring-head"><span>电机</span><span>EN</span><span>IN A</span><span>IN B</span><span>车轮侧</span><span>反向</span></div>{config.motorPins.map((pins:number[],i:number)=><div className="wiring-row" key={i}><b>M{i+1}</b>{pins.map((p,j)=><NumberInput key={j} label={`电机 ${i+1} ${['EN','IN A','IN B'][j]}`} value={p} min={0} max={39} onChange={v=>{const arr=config.motorPins.map((r:number[])=>[...r]);arr[i][j]=v;setCfg('motorPins',arr);}}/>)}<Choice value={config.motorSides[i]} label={`电机 ${i+1} 位置`} options={[["left","左"],["right","右"]]} onChange={v=>{const s=[...config.motorSides];s[i]=v;setCfg('motorSides',s);}}/><Switch checked={config.motorReverse[i]} aria-label={`电机 ${i+1} 反向`} onCheckedChange={v=>{const s=[...config.motorReverse];s[i]=v;setCfg('motorReverse',s);}}/></div>)}</div><div className="pin-row">{config.sensorPins.map((p:number,i:number)=><label key={i}>S{i+1} GPIO<NumberInput label={`S${i+1} GPIO`} value={p} min={0} max={39} onChange={v=>{const a=[...config.sensorPins];a[i]=v;setCfg('sensorPins',a);}}/></label>)}</div><div className="pin-row">{config.servoPins.map((p:number,i:number)=><label key={i}>{SERVO_NAMES[i]}<NumberInput label={SERVO_NAMES[i]+' GPIO'} value={p} min={0} max={39} onChange={v=>{const a=[...config.servoPins];a[i]=v;setCfg('servoPins',a);}}/></label>)}</div><p className="config-note">默认 M1、M2 在左侧，M3、M4 在右侧；传感器从车头左至右为 S1–S4。若与你的接线不同，请在这里调整。</p></TabsContent>
 <TabsContent value="arm"><div className="config-grid">{[['servoSpeed','舵机转速','°/s',60,600],['baseZero','底座朝前零位','°',0,180],['leftZero','left=90° 时大臂仰角','°',-40,120],['rightZero','right=90° 时小臂仰角','°',-120,120],['gripOpen','夹爪全开指令','°',0,180],['gripClosed','夹爪闭合指令','°',0,180]].map(([k,n,u,min,max]:any)=><div className="range-row" key={k}><label>{n}<span>{config[k]} {u}</span></label><Slider value={[config[k]]} min={min} max={max} step={1} onValueChange={v=>setCfg(k,v[0])} aria-label={n}/></div>)}{[['baseDir','底座方向'],['leftDir','大臂方向'],['rightDir','小臂方向']].map(([k,n])=><div className="switch-row" key={k}><label>{n}</label><Choice label={n} value={String(config[k])} options={[["1","正向"],["-1","反向"]]} onChange={v=>setCfg(k,Number(v))}/></div>)}{[['upperLength','大臂长度'],['foreLength','小臂长度']].map(([k,n])=><label className="length-field" key={k}>{n} / cm<NumberInput label={n} value={config[k]*100} min={5} max={30} onChange={v=>setCfg(k,v/100)}/></label>)}</div><p className="config-note">模型初始机械位置为 90° / 90° / 90° / 140°；attach() 后按库的默认 1500 μs 更新目标。舵机安装方向和零位请按实物校准。</p></TabsContent></Tabs></DialogContent></Dialog>
 <AlertDialog open={resetConfirm} onOpenChange={setResetConfirm}><AlertDialogContent><AlertDialogTitle>清空当前代码？</AlertDialogTitle><AlertDialogDescription>当前「{LABELS[program]}」中的代码将被清空。需要保留时可先导出。</AlertDialogDescription><div className="dialog-actions"><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction className="primary-button" onClick={()=>{updateCode('');const w=sim.current;if(w){w.source='';w.reset();refresh();}setDirty(false);setNotice('代码已清空，可以开始输入你的程序。');setResetConfirm(false);}}>清空代码</AlertDialogAction></div></AlertDialogContent></AlertDialog>
 </main>;
}
