import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation,START} from '../lib/sim/world.mjs';
import {compile,ArduinoVM} from '../lib/sim/interpreter.mjs';
import {PRESETS} from '../lib/sim/presets.mjs';
function sim(source=PRESETS.line,sensors=[0,1,1,0]){const w=new Simulation();w.manualSensors=sensors;w.load(source);return w;}
test('Original line program drives 4 wheels at 160 and moves from the left start',()=>{const w=sim();w.tick(100);assert.equal(w.error,null);assert.deepEqual(w.motor,[160,160,160,160]);assert.ok(w.pose.z<START.z);assert.equal(w.pose.x,START.x);});
test('Changing user code changes physical speed and direction',()=>{const original=sim(),slow=sim(PRESETS.line.replaceAll('160','80')),back=sim(PRESETS.line.replaceAll('160,true','160,false'));original.tick(1000);slow.tick(1000);back.tick(1000);assert.ok(Math.abs(original.distance/slow.distance-2)<1e-8);assert.ok(back.pose.z>START.z);assert.deepEqual(back.motor,[-160,-160,-160,-160]);});
test('Sensor branches execute motor writes; unmatched patterns preserve previous outputs',()=>{const w=sim(PRESETS.line,[0,0,1,1]);w.tick(30);assert.deepEqual(w.motor,[160,160,0,0]);assert.ok(w.pose.theta>START.theta);w.manualSensors=[1,0,1,0];w.tick(30);assert.deepEqual(w.motor,[160,160,0,0]);});
test('Full black gives 100ms stop then 500ms travel; sustained full black repeats i++',()=>{const w=sim(PRESETS.line,[1,1,1,1]);w.tick(99);assert.deepEqual(w.motor,[0,0,0,0]);assert.equal(w.vm.variables().i,1);w.tick(2);assert.deepEqual(w.motor,[130,130,130,130]);w.tick(501);assert.equal(w.vm.variables().i,2);assert.deepEqual(w.motor,[130,130,130,130]);});
test('Physical track sampling is 0110 on the starting straight and 1111 at the crossing',()=>{const w=new Simulation();assert.deepEqual(w.sensors,[0,1,1,0]);w.moveTo({x:(190-580)*.003,z:(540-850)*.003+w.config.sensorForward,theta:-Math.PI/2});assert.deepEqual(w.sensors,[1,1,1,1]);w.config.blackHigh=false;w.sample();assert.deepEqual(w.sensors,[0,0,0,0]);});
test('Original arm for loops set final target immediately, and delays occur in exact order',()=>{const w=sim(PRESETS.arm);w.tick(1);assert.equal(w.targets[3],155);assert.ok(w.angles[3]<155);w.tick(1000);assert.equal(w.targets[1],90);w.tick(1000);assert.equal(w.targets[0],32);w.tick(2999);assert.notEqual(w.targets[2],125);w.tick(1);assert.equal(w.targets[2],125);w.tick(3000);assert.equal(w.targets[3],140);assert.equal(w.error,null);});
test('Original arm complete sequence matches all loop endpoints and delay sum',()=>{const source=PRESETS.arm;const body=source.slice(source.indexOf('void loop()'));const expected=[];let time=0;const rx=/for\s*\([^;]+;[^;]+?([<>]=)\s*(\d+)\s*;[^)]+\)\s*\{\s*(\w+)\.write\(p\);\s*\}|delay\((\d+)\)/g;for(const m of body.matchAll(rx)){if(m[4])time+=Number(m[4]);else expected.push({time,name:m[3],angle:Number(m[2])});}const events=[];const states={};const vm=new ArduinoVM(compile(source),{servo:(pin,angle)=>{states[pin]=angle;},serial:()=>{},io:()=>0,fail:e=>{throw e;}});const pins={zhuan:14,left:26,right:25,zhua:27};for(let t=0;t<=time;t++){vm.runAt(t);for(const exp of expected.filter(e=>e.time===t))assert.equal(states[pins[exp.name]],exp.angle,`${exp.name} at ${t}ms`);}assert.equal(vm.error,null);assert.equal(vm.loopCount,1);assert.ok(time>=60000);console.log(`Original arm full loop ${time} ms, ${expected.length} servo movements verified`);});
test('Combined program pauses drive while arm delays and uses one shared ESP32 timeline',()=>{const w=sim(PRESETS.combined,[1,1,1,1]);w.tick(603);assert.equal(w.vm.variables().armDone,1);assert.deepEqual(w.motor,[0,0,0,0]);assert.equal(w.targets[3],155);const position={...w.pose};w.tick(5000);assert.deepEqual(w.motor,[0,0,0,0]);assert.deepEqual(w.pose,position);assert.equal(w.vm.variables().i,1);assert.equal(w.error,null);});
test('Blocking arm delay keeps motor outputs if user does not stop them',()=>{const src='#include <ESP32Servo.h>\nServo s; void setup(){ s.attach(14); digitalWrite(4,HIGH); digitalWrite(16,LOW); analogWrite(2,200); } void loop(){ s.write(50); delay(1000); }';const w=sim(src);w.tick(500);assert.equal(w.motor[0],200);assert.equal(w.targets[0],50);assert.ok(w.distance>0);});
test('Syntax errors, duplicate setup, unsupported API and infinite loops do not silently animate',()=>{assert.throws(()=>compile('void setup(){} void loop(){'),/花括号/);assert.throws(()=>compile('void setup(){} void setup(){} void loop(){}'),/重复定义/);const w=sim('void setup(){} void loop(){ unsupported(); }');w.tick(1);assert.match(w.error.message,/暂不支持/);const w2=sim('void setup(){} void loop(){while(true){} }');w2.tick(1);assert.match(w2.error.message,/死循环/);assert.deepEqual(w2.motor,[0,0,0,0]);});
test('Variable scope, integer division, millis and nonblocking state work',()=>{const w=sim('int i=0; int a=5/2; void setup(){} void loop(){ for(int p=0;p<5;p++){ i++; } if(millis()>=10) digitalWrite(4,HIGH); delay(5); }');w.tick(16);assert.equal(w.vm.variables().a,2);assert.equal(w.vm.variables().i,15);assert.equal(w.pins[4],1);});
test('Real track drive starts centered, crosses a transverse black line, then returns to middle-black without injected inputs',()=>{
 const w=new Simulation();w.load(PRESETS.line);assert.equal(w.manualSensors,null);assert.deepEqual(w.sensors,[0,1,1,0]);
 const transitions=[];let previous='';for(let ms=0;ms<6900;ms++){w.tick(1);const bits=w.sensors.join('');if(bits!==previous){transitions.push(bits);previous=bits;}}
 assert.deepEqual(transitions,['0110','1111','0110']);assert.equal(w.vm.variables().i,1);assert.equal(w.crossings,1);assert.equal(w.error,null);
});
