[package]
name = "just-lab-desktop"
version = "1.0.0"
description = "江苏科技大学机械创新实验室交流平台"
authors = ["江苏科技大学机械创新实验室"]
edition = "2021"

[lib]
name = "just_lab_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
